CREATE TABLE matches (
    id UUID PRIMARY KEY,
    tournament_id UUID NOT NULL,
    round_number INTEGER NOT NULL,
    match_number INTEGER NOT NULL,
    bracket_type VARCHAR(50) NOT NULL,
    position_label VARCHAR(255),
    race_to INTEGER NOT NULL DEFAULT 3,
    player1_id UUID,
    player2_id UUID,
    player1_score INTEGER NOT NULL DEFAULT 0,
    player2_score INTEGER NOT NULL DEFAULT 0,
    winner_id UUID,
    loser_id UUID,
    next_match_winner_id UUID,
    next_match_loser_id UUID,
    is_bye BOOLEAN NOT NULL DEFAULT FALSE,
    is_forfeit BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT fk_matches_tournament FOREIGN KEY (tournament_id) REFERENCES tournaments(id),
    CONSTRAINT fk_matches_player1 FOREIGN KEY (player1_id) REFERENCES player_registrations(id),
    CONSTRAINT fk_matches_player2 FOREIGN KEY (player2_id) REFERENCES player_registrations(id),
    CONSTRAINT fk_matches_winner FOREIGN KEY (winner_id) REFERENCES player_registrations(id),
    CONSTRAINT fk_matches_loser FOREIGN KEY (loser_id) REFERENCES player_registrations(id),
    CONSTRAINT fk_matches_next_winner FOREIGN KEY (next_match_winner_id) REFERENCES matches(id),
    CONSTRAINT fk_matches_next_loser FOREIGN KEY (next_match_loser_id) REFERENCES matches(id)
);
